// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService 下载服务，暴露给前端调用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * PauseDownload 暂停指定任务
 */
export function PauseDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(1120896033, id);
}

/**
 * ResumeDownload 继续指定任务
 */
export function ResumeDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(3920756602, id);
}

/**
 * SelectFolder 选择保存目录，返回空字符串表示用户取消
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(1240309125);
}

/**
 * SetConcurrency 运行时调整指定任务的并发 worker 数
 */
export function SetConcurrency(id: string, n: number): $CancellablePromise<void> {
    return $Call.ByID(661117986, id, n);
}

/**
 * StartDownload 下发整个下载任务，瓦片范围与 URL 都由 Go 侧计算。返回任务 ID
 */
export function StartDownload(job: model$0.DownloadJob): $CancellablePromise<string> {
    return $Call.ByID(1592691179, job);
}

/**
 * StopDownload 停止指定任务
 */
export function StopDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2737865145, id);
}
