// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadJob 一次完整的下载任务
 */
export interface DownloadJob {
    "rootPath": string;
    "sources": TileSource[] | null;
    "extent": number[];
    "zMin": number;
    "zMax": number;
    "concurrency": number;
    "writeConcurrency": number;
    "maxRetry": number;
    "skipExist": boolean;
    "socketsPerHost": number;
    "timeoutMs": number;
    "referer"?: string;
}

/**
 * Progress 下载进度（多任务队列快照）
 */
export interface Progress {
    "taskId": string;
    "layerId": string;
    "state": string;
    "total": number;
    "success": number;
    "failed": number;
    "skipped": number;
    "retried": number;
    "inFlight": number;
    "bytes": number;
    "tasks": TaskSummary[] | null;
}

/**
 * TaskSummary 队列中单个任务的进度快照
 */
export interface TaskSummary {
    "taskId": string;
    "layerId": string;
    "state": string;
    "total": number;
    "success": number;
    "failed": number;
    "skipped": number;
    "retried": number;
    "inFlight": number;
    "bytes": number;
    "concurrency": number;

    /**
     * QueuePos：相对活动任务的位置，0=正在运行/暂停，>0 为等待中的排队序号
     */
    "queuePos": number;
}

/**
 * TileSource 单个待下载图层
 */
export interface TileSource {
    "layerId": string;
    "projection": string;
    "urlRule": TileUrlRule;
}

/**
 * TileUrlRule 瓦片 URL 生成规则
 * 
 * 与 maptalks TileLayer.getTileUrl 行为保持一致：
 *   - {x} {y} {z}：瓦片坐标
 *   - {s}：子域名，取 subdomains[(x+y) % len]
 *   - {m} {n}：腾讯系图层专用，x/16 与 y/16
 *   - 其余占位符从 CustomTags 取值
 */
export interface TileUrlRule {
    "template": string;

    /**
     * Subdomains 元素既可能是数字也可能是字符串，用 any 承载
     */
    "subdomains"?: any[] | null;
    "hosts"?: string[] | null;
    "flipY"?: boolean;
    "customTags"?: { [_ in string]?: any } | null;
}
